version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build Angular App
          command: npm run build

  deploy:
    docker:
      - image: circleci/aws-cli
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Deploy to S3
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws s3 sync /workspace/dist/ s3://your-s3-bucket-name/
      - persist_to_workspace:
          root: /workspace
          paths:
            - dist

workflows:
  version: 2

  deploy_staging:
    jobs:
      - hold:
          type: approval
          name: deploy to staging?
          filters:
            branches:
              only:
                - staging
      - build:
          requires:
            - deploy to staging?
      - deploy:
          requires:
            - build

  deploy_prod:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
