version: 2.1
jobs:
  build:
    working_directory: ~/todo-app-fe
    docker:
      - image: cimg/node:16.20.1
    steps:
      - attach_workspace:
          at: .
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build Angular App
          command: |
            npm install -g @angular/cli@16
            ng build --configuration production
      - persist_to_workspace:
          root: .
          paths:
            - ./dist

  deploy:
    docker:
      - image: cimg/aws:2023.09
    parameters:
      bucket_name:
        type: string
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy to S3
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            pwd
            ls -a
            aws s3 sync dist/todo-app-fe/ s3://<< parameters.bucket_name >>/
      - persist_to_workspace:
          root: /workspace
          paths:
            - dist

workflows:
  version: 2

  deploy_staging:
    jobs:
      - hold:
          type: approval
          name: deploy to staging?
          filters:
            branches:
              only:
                - staging
      - build:
          requires:
            - deploy to staging?
      - deploy:
          bucket_name: staging-todo-app-website-hosting
          requires:
            - build
          context:
            - Staging_Context

  deploy_prod:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          bucket_name: todo-app-website-hosting
          requires:
            - build
          context:
            - Prod_Context
